// swift-tools-version: 5.9
// RELEASE MANIFEST — generated by scripts/make-release-manifest.sh for tag 1.2.0-dev.1.
// Consumers get the prebuilt, module-stable XCFramework: host Xcodes never compile SDK
// source, which is the mitigation for the Swift 6.1–6.3 optimizer task-teardown
// miscompilation (see .cursor/skills/swift-concurrency-task-shape/SKILL.md).
// To build from source instead, depend on the `main` branch or a source checkout.
import PackageDescription

let package = Package(
    name: "SimulaAdSDK",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "SimulaAdSDK",
            targets: ["SimulaAdSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SimulaAdSDK",
            url: "https://github.com/Simula-AI-SDK/simula-ad-sdk-swift/releases/download/1.2.0-dev.1/SimulaAdSDK.xcframework.zip",
            checksum: "00f049670e0fe37a47342e85a3261c8bb2b17cbca613f63e1214e6762c7c2b41"
        ),
    ]
)
