#!/usr/bin/env bash
#
# Rewrites Package.swift into the consumer binary manifest and adds the same
# artifact checksum to the CocoaPods HTTP source for a release tag.
#
# Distribution model: `main` keeps the source manifest (so `swift build && swift test`,
# CI, and @testable tests all work unchanged), while each release TAG carries a manifest
# whose target is the prebuilt XCFramework. SPM consumers pin tags/versions, so they
# resolve the binary; the repo itself always builds from source.
#
# The release workflow calls this after building the artifact. It commits the generated
# files only on the release tag; main retains the source Package.swift and checksum-free
# development podspec.

set -euo pipefail

cd "$(dirname "$0")/.."

VERSION="${1:?usage: make-release-manifest.sh <version> <checksum>}"
CHECKSUM="${2:?usage: make-release-manifest.sh <version> <checksum>}"

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z]+([.-][0-9A-Za-z]+)*)?$ ]] \
  || { echo "ERROR: version must be semantic versioning without a leading v"; exit 1; }
[[ "$CHECKSUM" =~ ^[0-9a-f]{64}$ ]] \
  || { echo "ERROR: checksum must be 64 lowercase hexadecimal characters"; exit 1; }

cat > Package.swift <<EOF
// swift-tools-version: 5.9
// RELEASE MANIFEST — generated by scripts/make-release-manifest.sh for tag ${VERSION}.
// Consumers get the prebuilt, module-stable XCFramework: host Xcodes never compile SDK
// source, which is the mitigation for the Swift 6.1–6.3 optimizer task-teardown
// miscompilation (see .cursor/skills/swift-concurrency-task-shape/SKILL.md).
// To build from source instead, depend on the \`main\` branch or a source checkout.
import PackageDescription

let package = Package(
    name: "SimulaAdSDK",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "SimulaAdSDK",
            targets: ["SimulaAdSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SimulaAdSDK",
            url: "https://github.com/Simula-AI-SDK/simula-ad-sdk-swift/releases/download/${VERSION}/SimulaAdSDK.xcframework.zip",
            checksum: "${CHECKSUM}"
        ),
    ]
)
EOF

ruby - "$CHECKSUM" <<'RUBY'
path = "SimulaAdSDK.podspec"
checksum = ARGV.fetch(0)
lines = File.readlines(path)
lines.reject! { |line| line.match?(/^\s*:sha256\s*=>/) }
http_index = lines.index { |line| line.match?(/^\s*:http\s*=>/) }
abort "ERROR: CocoaPods HTTP source not found" unless http_index
lines[http_index] = lines[http_index].rstrip.sub(/,?$/, ",") + "\n"
lines.insert(http_index + 1, "    :sha256 => \"#{checksum}\"\n")
File.write(path, lines.join)
RUBY

echo "Wrote release manifests for ${VERSION} (checksum ${CHECKSUM})"
