#!/usr/bin/env bash
#
# Rewrites Package.swift into the CONSUMER (binary) manifest for a release tag.
#
# Distribution model: `main` keeps the source manifest (so `swift build && swift test`,
# CI, and @testable tests all work unchanged), while each release TAG carries a manifest
# whose target is the prebuilt XCFramework. SPM consumers pin tags/versions, so they
# resolve the binary; the repo itself always builds from source.
#
# MANUAL release step (the workflow only builds + uploads the artifact — see
# .github/workflows/release.yml). After the workflow produced the draft release:
#   scripts/make-release-manifest.sh <version> <checksum>
# then commit, tag <version>, push the tag, and publish the draft against it.
# <checksum> is `swift package compute-checksum` of the zip (printed in the draft notes).

set -euo pipefail

cd "$(dirname "$0")/.."

VERSION="${1:?usage: make-release-manifest.sh <version> <checksum>}"
CHECKSUM="${2:?usage: make-release-manifest.sh <version> <checksum>}"

cat > Package.swift <<EOF
// swift-tools-version: 5.9
// RELEASE MANIFEST — generated by scripts/make-release-manifest.sh for tag ${VERSION}.
// Consumers get the prebuilt, module-stable XCFramework: host Xcodes never compile SDK
// source, which is the mitigation for the Swift 6.1–6.3 optimizer task-teardown
// miscompilation (see .cursor/skills/swift-concurrency-task-shape/SKILL.md).
// To build from source instead, depend on the \`main\` branch or a source checkout.
import PackageDescription

let package = Package(
    name: "SimulaAdSDK",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "SimulaAdSDK",
            targets: ["SimulaAdSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SimulaAdSDK",
            url: "https://github.com/Simula-AI-SDK/simula-ad-sdk-swift/releases/download/${VERSION}/SimulaAdSDK.xcframework.zip",
            checksum: "${CHECKSUM}"
        ),
    ]
)
EOF

echo "Wrote binary Package.swift for ${VERSION} (checksum ${CHECKSUM})"
